## 2. Create a random tensor with shape (7, 7)

In [2]:
import torch

rand_tensor_A= torch.rand(7, 7)
rand_tensor_A

tensor([[0.2428, 0.8836, 0.9265, 0.9713, 0.6276, 0.9759, 0.0615],
        [0.4950, 0.3607, 0.3947, 0.2789, 0.2114, 0.4951, 0.1164],
        [0.1330, 0.8115, 0.8124, 0.1079, 0.7079, 0.6021, 0.2451],
        [0.5920, 0.0851, 0.7068, 0.5345, 0.0179, 0.9874, 0.2630],
        [0.0884, 0.3655, 0.5286, 0.2778, 0.4349, 0.1744, 0.3873],
        [0.5177, 0.4837, 0.8315, 0.2208, 0.1133, 0.2102, 0.8818],
        [0.8874, 0.6920, 0.4031, 0.4048, 0.6845, 0.5955, 0.6262]])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
rand_tensor_B = torch.rand(1, 7)
torch.mm(rand_tensor_A, rand_tensor_B.T)

tensor([[2.0354],
        [0.9315],
        [1.5960],
        [1.1373],
        [1.1260],
        [1.7238],
        [1.8463]])

## 4. Set the random seed to 0 and do 2 & 3 over again.

In [4]:
torch.manual_seed(0)

rand_tensor_A = torch.rand(7, 7)
rand_tensor_B = torch.rand(1, 7)

mm = torch.mm(rand_tensor_A, rand_tensor_B.T)

mm, mm.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

* If there is, set the GPU random seed to 1234

In [10]:
if torch.cuda.is_available():
  torch.manual_seed(1234)
  print(True)

True


## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

`Device: cuda

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
         
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))`



In [42]:
torch.manual_seed(1234)

if torch.cuda.is_available():
  print("Device: cuda")

  rand_tensor_A = torch.rand(2, 3)
  rand_tensor_A = rand_tensor_A.to(device='cuda')

  rand_tensor_B = torch.rand(2, 3)
  rand_tensor_B = rand_tensor_B.to(device='cuda')

  print(rand_tensor_A, rand_tensor_A.device)
  print(rand_tensor_B, rand_tensor_B.device)



Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') cuda:0


## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:

`(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))`


In [43]:
mm = torch.mm(rand_tensor_A, rand_tensor_B.T)

mm, mm.device, mm.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([2, 2]))

## 8. Find the maximum and minimum values of the output of 7.

In [46]:
max = mm.max()

min = mm.min()

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7.

In [49]:
argmax = mm.argmax()
argmin = mm.argmin()

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [58]:
torch.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)
first_dim_removed = torch.squeeze(rand_tensor)

print(rand_tensor, rand_tensor.shape)
print(first_dim_removed, first_dim_removed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
